apiVersion: 1

datasources:
  - name: postgres-datasource
    uid: pgds
    orgId: 1
    type: postgres
    access: proxy
    url: postgres:5432
    database: berlin_bike_theft_db
    user: grafanareader
    basicAuth: false
    secureJsonData:
      password: "password"
    jsonData:
      sslmode: "disable"
      tlsAuth: false
      tlsAuthWithCACert: false
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false
    isDefault: true