{
 "title": "Berlin Bike Theft Dashboard",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  { "title": "Übersicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Anzahl der Fahrraddiebstähle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(schadenshoehe)\nFROM bike_thefts\nWHERE $__timeFilter(angelegt_am) AND versuch = 'Nein'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Angelegte Fahrraddiebstähle pro Tag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT angelegt_am AS time, COUNT(angelegt_am) AS value\nFROM bike_thefts\n-- WHERE $__timeFilter(\"ANGELEGT_AM\")\nGROUP BY angelegt_am\nORDER BY angelegt_am"
    }
   ]
  },
  {
   "title": "Fahrraddiebstähle pro Bezirk",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT bl.bez, gl.longitude, gl.latitude, COUNT(*) as anzahl\nFROM bike_thefts as bt\nJOIN berlin_lor as bl on bt.lor = bl.plr_id\nJOIN geo_lor as gl on bl.bez_id = gl.bez_id\nWHERE $__timeFilter(bt.angelegt_am) AND versuch = 'Nein'\nGROUP BY bez, longitude, latitude\nORDER BY anzahl DESC"
    }
   ]
  },
  {
   "title": "Insgesamte Schadenshöhe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT schadenshoehe\nFROM bike_thefts\nWHERE $__timeFilter(angelegt_am) AND versuch = 'Nein'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Art des Fahrrads",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*), art_des_fahrrads\nFROM bike_thefts\nWHERE $__timeFilter(angelegt_am) AND versuch = 'Nein'\nGROUP BY art_des_fahrrads\nORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Fahrraddiebstähle pro Bezirk",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT bez, COUNT(*) as anzahl\nFROM bike_thefts as bt\nJOIN berlin_lor as bl on bt.lor = bl.plr_id\nWHERE $__timeFilter(bt.angelegt_am) AND versuch = 'Nein'\nGROUP BY bez\nORDER BY anzahl DESC"
    }
   ]
  },
  { "title": "Ort des Diebstahls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Fahrraddiebstähle pro Planungsraum",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT gl.pgr_name, gl.longitude, gl.latitude, COUNT(*) as anzahl\nFROM bike_thefts as bt\nJOIN berlin_lor as bl on bt.lor = bl.plr_id\nJOIN prognoseraeume_lor as gl on bl.pgr_id = gl.pgr_id\nWHERE $__timeFilter(bt.angelegt_am) AND versuch = 'Nein'\nGROUP BY pgr_name, longitude, latitude\nORDER BY anzahl DESC\n"
    }
   ]
  },
  {
   "title": "Fahrraddiebstähle pro Bezirksregion",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT gl.bzr_name, gl.longitude, gl.latitude, COUNT(*) as anzahl\nFROM bike_thefts as bt\nJOIN berlin_lor as bl on bt.lor = bl.plr_id\nJOIN bezirksregionen_lor as gl on bl.bzr_id = gl.bzr_id\nWHERE $__timeFilter(bt.angelegt_am) AND versuch = 'Nein'\nGROUP BY bzr_name, longitude, latitude\nORDER BY anzahl DESC\n"
    }
   ]
  },
  {
   "title": "Fahrraddiebstähle pro Planungsraum",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT gl.plr_name, gl.longitude, gl.latitude, COUNT(*) as anzahl\nFROM bike_thefts as bt\nJOIN berlin_lor as bl on bt.lor = bl.plr_id\nJOIN planungsraeume_lor as gl on bl.plr_id = gl.plr_id\nWHERE $__timeFilter(bt.angelegt_am) AND versuch = 'Nein'\nGROUP BY plr_name, longitude, latitude\nORDER BY anzahl DESC\n"
    }
   ]
  },
  {
   "title": "Fahrraddiebstähle pro Prognoseraum",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT bez, pgr, COUNT(*) as anzahl\nFROM bike_thefts as bt\nJOIN berlin_lor as bl on bt.lor = bl.plr_id\nWHERE $__timeFilter(bt.angelegt_am) AND versuch = 'Nein'\nGROUP BY bez, pgr\nORDER BY anzahl DESC"
    }
   ]
  },
  {
   "title": "Fahrraddiebstähle pro Bezirksregion",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT bez, bzr, COUNT(*) as anzahl\nFROM bike_thefts as bt\nJOIN berlin_lor as bl on bt.lor = bl.plr_id\nWHERE $__timeFilter(bt.angelegt_am) AND versuch = 'Nein'\nGROUP BY bez, bzr\nORDER BY anzahl DESC"
    }
   ]
  },
  {
   "title": "Fahrraddiebstähle pro Planungsraum",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT bez, plr, COUNT(*) as anzahl\nFROM bike_thefts as bt\nJOIN berlin_lor as bl on bt.lor = bl.plr_id\nWHERE $__timeFilter(bt.angelegt_am) AND versuch = 'Nein'\nGROUP BY bez, plr\nORDER BY anzahl DESC"
    }
   ]
  },
  { "title": "Tatzeitpunkt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Tatzeitraum in Stunden",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT (EXTRACT(EPOCH FROM tatzeit_ende) - EXTRACT(EPOCH FROM tatzeit_anfang))/3600 AS tatzeitraum_stunden\nFROM bike_thefts \nWHERE $__timeFilter(angelegt_am) AND versuch = 'Nein'\nORDER BY tatzeitraum_stunden"
    }
   ]
  },
  {
   "title": "Tatzeit Anfang (Uhrzeit)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT tatzeit_anfang_stunde, COUNT(*)\nFROM bike_thefts\nWHERE $__timeFilter(tatzeit_anfang_datum) AND versuch = 'Nein'\nGROUP BY tatzeit_anfang_stunde\nORDER BY tatzeit_anfang_stunde"
    }
   ]
  },
  {
   "title": "Tatzeit Ende (Uhrzeit)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT tatzeit_ende_stunde, COUNT(*)\nFROM bike_thefts\nWHERE $__timeFilter(tatzeit_ende_datum) AND versuch = 'Nein'\nGROUP BY tatzeit_ende_stunde\nORDER BY tatzeit_ende_stunde"
    }
   ]
  },
  {
   "title": "Tatzeit Anfang (Wochentag)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "WITH tatzeit_anfang AS (\n  SELECT\n    tatzeit_anfang_datum,\n    TRIM(TO_CHAR(tatzeit_anfang_datum, 'Day')) AS wochentag, \n    EXTRACT(ISODOW FROM tatzeit_anfang_datum) AS wochentag_num\n  FROM\n    bike_thefts\n  WHERE $__timeFilter(tatzeit_anfang_datum) AND versuch = 'Nein'\n)\n\nSELECT wochentag, COUNT(wochentag) FROM tatzeit_anfang\nGROUP BY wochentag, wochentag_num\nORDER BY wochentag_num"
    }
   ]
  },
  {
   "title": "Tatzeit Ende (Wochentag)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "rawSql": "WITH tatzeit_ende AS (\n  SELECT\n    tatzeit_ende_datum,\n    TRIM(TO_CHAR(tatzeit_ende_datum, 'Day')) AS wochentag, \n    EXTRACT(ISODOW FROM tatzeit_ende_datum) AS wochentag_num\n  FROM\n    bike_thefts\n  WHERE $__timeFilter(tatzeit_ende_datum) AND versuch = 'Nein'\n)\n\nSELECT wochentag, COUNT(wochentag) FROM tatzeit_ende\nGROUP BY wochentag, wochentag_num\nORDER BY wochentag_num"
    }
   ]
  },
  { "title": "Informationen über den Delikt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Art des Delikts",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT delikt, COUNT(*)\nFROM bike_thefts\nWHERE $__timeFilter(angelegt_am) AND versuch = 'Nein'\nGROUP BY delikt\nORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Versuchter Fahrraddiebstahl",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT versuch, COUNT(*)\nFROM bike_thefts\nWHERE $__timeFilter(angelegt_am)\nGROUP BY versuch\nORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Art des Diebstahls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\n  'Einfacher Diebstahl' AS diebstahlstyp,\n  COUNT(*) AS anzahl\nFROM bike_thefts\nWHERE LOWER(erfassungsgrund) LIKE '%einfach%'\n  AND $__timeFilter(angelegt_am)\n  AND versuch = 'Nein'\n  \nUNION ALL\n\nSELECT\n  'Schwerer Diebstahl' AS diebstahlstyp,\n  COUNT(*) AS anzahl\nFROM bike_thefts\nWHERE LOWER(erfassungsgrund) LIKE '%schwer%'\n  AND $__timeFilter(angelegt_am)"
    }
   ]
  },
  { "title": "Schadenshöhe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Verteilung der Schadenshöhe",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT schadenshoehe\nFROM bike_thefts\nWHERE $__timeFilter(angelegt_am) AND versuch = 'Nein'\nGROUP BY schadenshoehe\nORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Schadenshöhe nach Art des Fahrrads (in €)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "rawSql": "SELECT \n  art_des_fahrrads AS \"Art des Fahrrads\",\n  COUNT(CASE WHEN schadenshoehe <= 500 THEN 1 END) AS \"Unter 500\",\n  COUNT(CASE WHEN schadenshoehe > 500 AND schadenshoehe <= 1000 THEN 1 END) AS \"501 - 1000\",\n  COUNT(CASE WHEN schadenshoehe > 1000 AND schadenshoehe <= 1500 THEN 1 END) AS \"1001 - 1500\",\n  COUNT(CASE WHEN schadenshoehe > 1500 AND schadenshoehe <= 2000 THEN 1 END) AS \"1501 - 2000\",\n  COUNT(CASE WHEN schadenshoehe > 2000 AND schadenshoehe <= 2500 THEN 1 END) AS \"2001 - 2500\",\n  COUNT(CASE WHEN schadenshoehe > 2500 AND schadenshoehe <= 3000 THEN 1 END) AS \"2501 - 3000\",\n  COUNT(CASE WHEN schadenshoehe > 3000 AND schadenshoehe <= 3500 THEN 1 END) AS \"3001 - 3500\",\n  COUNT(CASE WHEN schadenshoehe > 3500 THEN 1 END) AS \"Über 3500\"\nFROM bike_thefts\nWHERE $__timeFilter(angelegt_am) AND versuch = 'Nein'\nGROUP BY art_des_fahrrads\nORDER BY COUNT(*) DESC"
    }
   ]
  }
 ]
}